### cria menino
POST http://localhost:3000/api/dataRead
Content-Type: application/json

{
  "id_device": "2451",
  "location": "são pituba da capixaiboinha",
  "recived_data": "ta frio"
}

###

### lisata
GET http://localhost:3000/api/devices

###
@id = 68f7ca6f635614f8c6f55703

### buca
GET http://localhost:3000/api/devices/{{id}}

###

### atualiza
PUT http://localhost:3000/api/devices/{{id}}
Content-Type: application/json

{
  "id_device": "242351",
  "location": "são pituba da capixaiboinha 2",
  "recived_data": "ta frio nada :p"
}

###

### deleta
DELETE http://localhost:3000/api/devices/{{id}}

